Repository teleporthq/teleport-code-generators, pull requests merged in 2019-10, with the labels that each got.

#379 feat: string blacklists on mappings and regex validation for some strings in the UIDL
  examples/test-samples/component-invalid-sample.json
  examples/test-samples/component-sample.json
  examples/test-samples/project-invalid-sample.json
  examples/test-samples/project-sample.json
  examples/uidl-samples/project.json
  packages/teleport-component-generator-react/src/react-mapping.json
  packages/teleport-component-generator-stencil/src/stencil-mapping.json
  packages/teleport-shared/__tests__/node-handlers/node-to-html/index.ts
  packages/teleport-shared/src/node-handlers/node-to-html/index.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/index.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-uidl-resolver/__tests__/mapping.json
  packages/teleport-uidl-resolver/__tests__/resolver.ts
  packages/teleport-uidl-resolver/__tests__/utils.ts
  packages/teleport-uidl-resolver/src/html-mapping.json
  packages/teleport-uidl-resolver/src/resolver.ts
  packages/teleport-uidl-resolver/src/utils.ts
  packages/teleport-uidl-validator/src/uidl-schemas/component.json
  scripts/watcher.js
Labels: bug

#385 fix: forced scoping added for css plugin and set on vue, react, preact
  packages/teleport-component-generator-preact/src/index.ts
  packages/teleport-component-generator-react/src/index.ts
  packages/teleport-component-generator-vue/src/index.ts
  packages/teleport-plugin-css/src/index.ts
Labels: enhancement

#387 fix(code-generator): fixed bug for picking preact template by default
  packages/teleport-code-generator/src/index.ts
Labels: preact generators

#388 feat(gridsome): generating projects based on gridsome
  packages/teleport-code-generator/package.json
  packages/teleport-code-generator/src/index.ts
  packages/teleport-project-generator-gridsome/README.md
  packages/teleport-project-generator-gridsome/__tests__/end2end/index.ts
  packages/teleport-project-generator-gridsome/__tests__/end2end/template-definition.json
  packages/teleport-project-generator-gridsome/package.json
  packages/teleport-project-generator-gridsome/src/gridsome-project-mapping.json
  packages/teleport-project-generator-gridsome/src/gridsome-project-template.ts
  packages/teleport-project-generator-gridsome/src/index.ts
  packages/teleport-project-generator-gridsome/tsconfig-cjs.json
  packages/teleport-project-generator-gridsome/tsconfig-esm.json
  packages/teleport-test/package.json
  packages/teleport-test/src/constants.ts
  packages/teleport-test/src/packer.ts
  packages/teleport-test/src/standalone.ts
  packages/teleport-types/src/generators.ts
Labels: vue generators

#389 fix: custom mapping logic for navlinks and <a> tags
  packages/teleport-project-generator-next/src/next-mapping.json
  packages/teleport-uidl-resolver/src/utils.ts
Labels: bug

#391 fix(gridsome-mapping): adding mappings for gridsome
  packages/teleport-project-generator-gridsome/src/gridsome-project-mapping.json
Labels: vue generators

#384 feat(proj-gen-gatsby): support for project generators using gatsby
  packages/teleport-code-generator/package.json
  packages/teleport-code-generator/src/index.ts
  packages/teleport-component-generator-preact/src/index.ts
  packages/teleport-plugin-common/src/builders/ast-builders.ts
  packages/teleport-plugin-css-modules/src/index.ts
  packages/teleport-project-generator-gatsby/README.md
  packages/teleport-project-generator-gatsby/__tests__/end2end/index.ts
  packages/teleport-project-generator-gatsby/__tests__/end2end/template-definition.json
  packages/teleport-project-generator-gatsby/package.json
  packages/teleport-project-generator-gatsby/src/gatsby-mapping.json
  packages/teleport-project-generator-gatsby/src/index.ts
  packages/teleport-project-generator-gatsby/src/project-template.ts
  packages/teleport-project-generator-gatsby/src/utils.ts
  packages/teleport-project-generator-gatsby/tsconfig-cjs.json
  packages/teleport-project-generator-gatsby/tsconfig-esm.json
  packages/teleport-project-generator-next/src/utils.ts
  packages/teleport-test/package.json
  packages/teleport-test/src/constants.ts
  packages/teleport-test/src/packer.ts
  packages/teleport-test/src/standalone.ts
  packages/teleport-types/src/generators.ts
Labels: react generators

#398 feat(gatsby-proj): support for custom manifest in gatsby
  packages/teleport-project-generator-gatsby/src/index.ts
  packages/teleport-project-generator-gatsby/src/project-template.ts
  packages/teleport-project-generator-gatsby/src/utils.ts
Labels: react generators

#400 fix: mapping sync with playground
  packages/teleport-code-generator/src/index.ts
  packages/teleport-component-generator-reactnative/src/index.ts
  packages/teleport-component-generator-reactnative/src/react-native-mapping.json
  packages/teleport-plugin-react-styled-components/src/index.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
  packages/teleport-types/src/generators.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-uidl-resolver/src/html-mapping.json
  packages/teleport-uidl-resolver/src/resolver.ts
  packages/teleport-uidl-resolver/src/utils.ts
Labels: core
