Repository teleporthq/teleport-code-generators, pull requests merged in 2019-07, with the labels that each got.

#276 fix(vue-base-com): Handling non-element root nodes for vue
  packages/teleport-component-generator-vue/__tests__/integration/component-non-element-root.ts
  packages/teleport-plugin-vue-base-component/src/index.ts
Labels: bug

#298 repl-component: initial setup
  package.json
  packages/teleport-repl-component/.gitignore
  packages/teleport-repl-component/README.md
  packages/teleport-repl-component/package.json
  packages/teleport-repl-component/src/components.d.ts
  packages/teleport-repl-component/src/components/editor/editor.css
  packages/teleport-repl-component/src/components/editor/editor.tsx
  packages/teleport-repl-component/src/components/editor/readme.md
  packages/teleport-repl-component/src/index.html
  packages/teleport-repl-component/src/index.ts
  packages/teleport-repl-component/stencil.config.ts
  packages/teleport-repl-component/tsconfig.json
  yarn.lock
Labels: repl

#305 refactor(shared): renames, reusability, tests, cleanup, etc.
  packages/teleport-component-generator/src/builder/generators/js-ast-to-code.ts
  packages/teleport-plugin-import-statements/src/index.ts
  packages/teleport-plugin-react-app-routing/package.json
  packages/teleport-plugin-react-app-routing/src/index.ts
  packages/teleport-plugin-react-app-routing/src/utils.ts
  packages/teleport-plugin-react-base-component/src/node-handlers.ts
  packages/teleport-plugin-react-base-component/src/utils.ts
  packages/teleport-plugin-react-css-modules/package.json
  packages/teleport-plugin-react-css-modules/src/index.ts
  packages/teleport-plugin-react-inline-styles/package.json
  packages/teleport-plugin-react-inline-styles/src/index.ts
  packages/teleport-plugin-react-jss/package.json
  packages/teleport-plugin-react-jss/src/index.ts
  packages/teleport-plugin-react-jss/src/utils.ts
  packages/teleport-plugin-react-styled-components/src/index.ts
  packages/teleport-plugin-react-styled-jsx/__tests__/utils.ts
  packages/teleport-plugin-react-styled-jsx/src/index.ts
  packages/teleport-plugin-react-styled-jsx/src/utils.ts
  packages/teleport-project-generator-react-next/src/utils.ts
  packages/teleport-shared/__tests__/builders/ast-builders.ts
  packages/teleport-shared/__tests__/utils/ast-jsx-utils.ts
  packages/teleport-shared/src/builders/ast-builders.ts
  packages/teleport-shared/src/builders/css-builders.ts
  packages/teleport-shared/src/utils/ast-jsx-utils.ts
  packages/teleport-types/src/generators.ts
Labels: refactoring

#307 chore(watcher.js): A Watcher to that triggers for changes in file and rebuild the package
  package.json
  scripts/watcher.js
  tsconfig.json
  yarn.lock
Labels: dev experience

#309 fix(plugin-styles): Fix generation of empty styles
  packages/teleport-plugin-react-css-modules/src/index.ts
  packages/teleport-plugin-react-inline-styles/src/index.ts
  packages/teleport-plugin-react-jss/src/index.ts
  packages/teleport-plugin-react-styled-components/src/index.ts
  packages/teleport-plugin-react-styled-jsx/src/index.ts
  packages/teleport-plugin-vue-css/src/index.ts
Labels: style flavours

#311 (feat): Added a tab to show css file
  packages/teleport-repl-component/src/components/editor/editor.css
  packages/teleport-repl-component/src/components/editor/editor.tsx
  packages/teleport-repl-component/src/index.html
Labels: repl

#313 refactor(repl-component): Watcher first builds all packages before wa…
  scripts/watcher.js
Labels: dev experience

#325 refactor: standard file and chunk types
  packages/teleport-component-generator-stencil/__tests__/end2end/index.ts
  packages/teleport-component-generator-stencil/package.json
  packages/teleport-component-generator-stencil/src/index.ts
  packages/teleport-component-generator/__tests__/index.ts
  packages/teleport-component-generator/src/assembly-line/utils.ts
  packages/teleport-component-generator/src/builder/index.ts
  packages/teleport-plugin-import-statements/src/index.ts
  packages/teleport-plugin-preact-base-component/__tests__/index.ts
  packages/teleport-plugin-preact-base-component/src/index.ts
  packages/teleport-plugin-react-app-routing/__tests__/index.ts
  packages/teleport-plugin-react-app-routing/src/index.ts
  packages/teleport-plugin-react-base-component/__tests__/index.ts
  packages/teleport-plugin-react-base-component/src/index.ts
  packages/teleport-plugin-react-css-modules/__tests__/index.ts
  packages/teleport-plugin-react-css-modules/src/index.ts
  packages/teleport-plugin-react-inline-styles/__tests__/index.ts
  packages/teleport-plugin-react-jss/__tests__/index.ts
  packages/teleport-plugin-react-jss/src/index.ts
  packages/teleport-plugin-react-proptypes/__tests__/index.ts
  packages/teleport-plugin-react-proptypes/src/index.ts
  packages/teleport-plugin-react-styled-components/__tests__/index.ts
  packages/teleport-plugin-react-styled-components/src/index.ts
  packages/teleport-plugin-react-styled-jsx/__tests__/index.ts
  packages/teleport-plugin-stencil-base-component/__tests__/index.ts
  packages/teleport-plugin-stencil-base-component/src/index.ts
  packages/teleport-plugin-stencil-css/__tests__/index.ts
  packages/teleport-plugin-stencil-css/src/index.ts
  packages/teleport-plugin-vue-app-routing/__tests__/index.ts
  packages/teleport-plugin-vue-app-routing/src/index.ts
  packages/teleport-plugin-vue-base-component/__tests__/index.ts
  packages/teleport-plugin-vue-base-component/src/index.ts
  packages/teleport-plugin-vue-css/__tests__/index.ts
  packages/teleport-plugin-vue-css/src/index.ts
  packages/teleport-project-generator-react-next/src/utils.ts
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-shared/src/constants/index.ts
  packages/teleport-types/src/generators.ts
Labels: refactoring

#318 fix(styled-comp): Converting to camel case when passing as props
  packages/teleport-component-generator-react/__tests__/integration/component-style.ts
  packages/teleport-component-generator-react/__tests__/integration/component-with-valid-style.json
  packages/teleport-component-generator-react/package.json
  packages/teleport-plugin-react-styled-components/src/index.ts
  packages/teleport-shared/src/builders/uidl-builders.ts
Labels: bug

#320 feat(preact-project-gen): A Preact project generator
  package.json
  packages/teleport-plugin-react-app-routing/src/index.ts
  packages/teleport-plugin-react-app-routing/src/utils.ts
  packages/teleport-project-generator-preact-basic/README.md
  packages/teleport-project-generator-preact-basic/__tests__/end2end/index.ts
  packages/teleport-project-generator-preact-basic/__tests__/end2end/template-definition.json
  packages/teleport-project-generator-preact-basic/package.json
  packages/teleport-project-generator-preact-basic/src/index.ts
  packages/teleport-project-generator-preact-basic/src/preact-project-mapping.json
  packages/teleport-project-generator-preact-basic/tsconfig-cjs.json
  packages/teleport-project-generator-preact-basic/tsconfig-esm.json
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-project-generator/src/index.ts
  packages/teleport-project-generator/src/types.ts
  packages/teleport-project-generator/src/utils.ts
  packages/teleport-project-packer-test/package.json
  packages/teleport-project-packer-test/src/constants.ts
  packages/teleport-project-packer-test/src/index.ts
Labels: preact generators
