Repository teleporthq/teleport-code-generators, pull requests merged in 2019-08, with the labels that each got.

#328 feat(postprocessors): factory functions defined with options for configurability
  packages/teleport-component-generator-stencil/src/index.ts
  packages/teleport-component-generator/__tests__/index.ts
  packages/teleport-component-generator/src/index.ts
  packages/teleport-postprocessor-prettier-html/src/index.ts
  packages/teleport-postprocessor-prettier-js/src/index.ts
  packages/teleport-postprocessor-vue-file/src/index.ts
  packages/teleport-shared/src/constants/index.ts
  packages/teleport-types/src/generators.ts
Labels: core

#327 fix(slots): restrictions for slot node fallback and separate handling for native / prop based slot
  packages/teleport-shared/__tests__/node-handlers/node-to-jsx/index.ts
  packages/teleport-shared/src/builders/uidl-builders.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/index.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-uidl-validator/src/parser/index.ts
Labels: core

#329 feat(Builders): Added project-builders and tests
  packages/teleport-shared/__tests__/builders/project-builders.ts
  packages/teleport-shared/src/builders/project-builders.ts
Labels: dev experience

#330 refactor(vue): extract html generation syntax into shared package
  packages/teleport-component-generator-stencil/src/index.ts
  packages/teleport-component-generator/__tests__/index.ts
  packages/teleport-component-generator/src/assembly-line/index.ts
  packages/teleport-component-generator/src/assembly-line/utils.ts
  packages/teleport-component-generator/src/index.ts
  packages/teleport-plugin-import-statements/src/index.ts
  packages/teleport-plugin-preact-base-component/src/index.ts
  packages/teleport-plugin-react-app-routing/src/index.ts
  packages/teleport-plugin-react-base-component/src/index.ts
  packages/teleport-plugin-react-css-modules/__tests__/index.ts
  packages/teleport-plugin-react-css-modules/src/index.ts
  packages/teleport-plugin-react-inline-styles/__tests__/index.ts
  packages/teleport-plugin-react-jss/__tests__/index.ts
  packages/teleport-plugin-react-jss/src/index.ts
  packages/teleport-plugin-react-proptypes/__tests__/index.ts
  packages/teleport-plugin-react-proptypes/src/index.ts
  packages/teleport-plugin-react-styled-components/__tests__/index.ts
  packages/teleport-plugin-react-styled-components/src/index.ts
  packages/teleport-plugin-react-styled-jsx/__tests__/index.ts
  packages/teleport-plugin-stencil-base-component/src/index.ts
  packages/teleport-plugin-stencil-css/__tests__/index.ts
  packages/teleport-plugin-stencil-css/src/index.ts
  packages/teleport-plugin-vue-app-routing/src/index.ts
  packages/teleport-plugin-vue-base-component/src/constants.ts
  packages/teleport-plugin-vue-base-component/src/index.ts
  packages/teleport-plugin-vue-base-component/src/utils.ts
  packages/teleport-plugin-vue-css/__tests__/index.ts
  packages/teleport-plugin-vue-css/src/index.ts
  packages/teleport-project-generator-react-next/src/utils.ts
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-shared/__tests__/node-handlers/node-to-html/index.ts
  packages/teleport-shared/src/node-handlers/node-to-html/index.ts
  packages/teleport-shared/src/node-handlers/node-to-html/types.ts
  packages/teleport-shared/src/node-handlers/node-to-html/utils.ts
  packages/teleport-types/src/generators.ts
Labels: refactoring

#331 refactor(core): template generation syntax is now configurable from base plugins
  packages/teleport-component-generator-vue/__tests__/integration/component-non-element-root.ts
  packages/teleport-component-generator/src/resolver/utils.ts
  packages/teleport-plugin-vue-base-component/src/index.ts
  packages/teleport-plugin-vue-base-component/src/utils.ts
  packages/teleport-shared/__tests__/node-handlers/node-to-html/index.ts
  packages/teleport-shared/src/node-handlers/node-to-html/constants.ts
  packages/teleport-shared/src/node-handlers/node-to-html/index.ts
  packages/teleport-shared/src/node-handlers/node-to-html/types.ts
  packages/teleport-shared/src/node-handlers/node-to-html/utils.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/utils.ts
  packages/teleport-types/src/uidl.ts
Labels: core

#336 refactor(css-modules): classname generation optimization and tests for multiple cases
  packages/teleport-plugin-react-css-modules/__tests__/index.ts
  packages/teleport-plugin-react-css-modules/__tests__/mocks.ts
  packages/teleport-plugin-react-css-modules/src/index.ts
Labels: refactoring

#334 refactor components generated in own folder
  packages/teleport-component-generator-preact/src/index.ts
  packages/teleport-component-generator/src/index.ts
  packages/teleport-plugin-react-app-routing/src/index.ts
  packages/teleport-plugin-react-css-modules/src/index.ts
  packages/teleport-plugin-stencil-css/src/index.ts
  packages/teleport-plugin-vue-app-routing/src/index.ts
  packages/teleport-project-generator-next/src/index.ts
  packages/teleport-project-generator-next/src/utils.ts
  packages/teleport-project-generator-nuxt/src/index.ts
  packages/teleport-project-generator-preact/src/index.ts
  packages/teleport-project-generator/__tests__/file-handlers.ts
  packages/teleport-project-generator/__tests__/index.ts
  packages/teleport-project-generator/__tests__/mocks.ts
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-project-generator/src/index.ts
  packages/teleport-project-generator/src/types.ts
  packages/teleport-project-generator/src/utils.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
  packages/teleport-types/src/generators.ts
  packages/teleport-types/src/uidl.ts
Labels: core

#338 refactor(css): teleport-plugin-css now works for both html templates and jsx code chunks
  packages/teleport-component-generator-angular/src/index.ts
  packages/teleport-component-generator-preact/package.json
  packages/teleport-component-generator-preact/src/index.ts
  packages/teleport-component-generator-react/__tests__/integration/component-style.ts
  packages/teleport-component-generator-react/package.json
  packages/teleport-component-generator-react/src/index.ts
  packages/teleport-component-generator-stencil/package.json
  packages/teleport-component-generator-stencil/src/index.ts
  packages/teleport-component-generator-vue/src/index.ts
  packages/teleport-plugin-angular-base-component/src/constants.ts
  packages/teleport-plugin-angular-base-component/src/utils.ts
  packages/teleport-plugin-css/__tests__/index.ts
  packages/teleport-plugin-css/src/index.ts
  packages/teleport-plugin-import-statements/src/index.ts
  packages/teleport-plugin-stencil-base-component/src/constants.ts
  packages/teleport-plugin-stencil-css/README.md
  packages/teleport-plugin-stencil-css/__tests__/index.ts
  packages/teleport-plugin-stencil-css/package.json
  packages/teleport-plugin-stencil-css/src/index.ts
  packages/teleport-plugin-stencil-css/tsconfig-cjs.json
  packages/teleport-plugin-stencil-css/tsconfig-esm.json
  packages/teleport-shared/src/builders/ast-builders.ts
  packages/teleport-types/src/generators.ts
  packages/teleport-types/src/uidl.ts
Labels: style flavours

#343 refactor: small fixes
  packages/teleport-component-generator-preact/src/index.ts
  packages/teleport-plugin-angular-base-component/src/utils.ts
  packages/teleport-plugin-vue-base-component/src/utils.ts
  packages/teleport-shared/__tests__/builders/ast-builders.ts
  packages/teleport-shared/__tests__/node-handlers/node-to-jsx/utils.ts
  packages/teleport-shared/__tests__/utils/ast-utils.ts
  packages/teleport-shared/src/builders/ast-builders.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/index.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/utils.ts
  packages/teleport-shared/src/utils/ast-js-utils.ts
  packages/teleport-types/src/generators.ts
  packages/teleport-uidl-validator/src/validator/utils.ts
Labels: bug

#344 Feat/root node restricted to type element
  packages/teleport-component-generator-react/__tests__/integration/component-non-element-root.ts
  packages/teleport-component-generator-react/__tests__/integration/component-with-conditional-root-array-child-node.json
  packages/teleport-component-generator-react/__tests__/integration/component-with-conditional-root-string-child-node.json
  packages/teleport-component-generator-vue/__tests__/integration/component-non-element-root.ts
  packages/teleport-plugin-preact-base-component/src/utils.ts
  packages/teleport-plugin-react-base-component/src/index.ts
  packages/teleport-plugin-react-base-component/src/utils.ts
  packages/teleport-plugin-react-styled-jsx/__tests__/index.ts
  packages/teleport-plugin-react-styled-jsx/src/index.ts
  packages/teleport-plugin-stencil-base-component/src/utils.ts
  packages/teleport-plugin-vue-base-component/src/index.ts
  packages/teleport-project-generator/src/utils.ts
  packages/teleport-project-packer-test/src/index.ts
  packages/teleport-shared/__tests__/node-handlers/node-to-jsx/index.ts
  packages/teleport-shared/src/builders/uidl-builders.ts
  packages/teleport-shared/src/node-handlers/node-to-html/index.ts
  packages/teleport-shared/src/node-handlers/node-to-html/types.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/constants.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/index.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/types.ts
  packages/teleport-shared/src/node-handlers/node-to-jsx/utils.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-uidl-validator/src/parser/index.ts
  packages/teleport-uidl-validator/src/uidl-schemas/component.json
Labels: core

#347 refactor(stencil-app-routing): casting dependencies to UIDLDependency…
  packages/teleport-plugin-stencil-app-routing/src/constants.ts
Labels: bug

#348 fix(preact-generator): Picking a inbuilt index template and injecting custom tags
  packages/teleport-project-generator-preact/package.json
  packages/teleport-project-generator-preact/src/constants.ts
  packages/teleport-project-generator-preact/src/index.ts
  packages/teleport-project-generator-stencil/src/index.ts
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-types/src/generators.ts
Labels: preact generators

#353 refactor(seo): handling default title and canonical link
  examples/uidl-samples/project.json
  packages/teleport-component-generator/src/resolver/utils.ts
  packages/teleport-plugin-jsx-head-config/__tests__/index.ts
  packages/teleport-plugin-jsx-head-config/src/index.ts
  packages/teleport-plugin-vue-head-config/__tests__/index.ts
  packages/teleport-plugin-vue-head-config/src/index.ts
  packages/teleport-project-generator-next/src/utils.ts
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-project-generator/src/index.ts
  packages/teleport-project-generator/src/utils.ts
  packages/teleport-types/src/uidl.ts
Labels: core

#351 fix(angular-base): Handling multiple statements in event handlers
  packages/teleport-component-generator-angular/__tests__/end2end/index.ts
  packages/teleport-component-generator-vue/__tests__/end2end/index.ts
  packages/teleport-plugin-angular-base-component/src/index.ts
  packages/teleport-plugin-angular-base-component/src/utils.ts
  packages/teleport-plugin-vue-base-component/src/utils.ts
  packages/teleport-shared/src/builders/uidl-builders.ts
  packages/teleport-shared/src/node-handlers/node-to-html/constants.ts
  packages/teleport-shared/src/node-handlers/node-to-html/types.ts
  packages/teleport-shared/src/node-handlers/node-to-html/utils.ts
  packages/teleport-shared/src/utils/ast-js-utils.ts
Labels: angular generators, bug
