Repository teleporthq/teleport-code-generators, pull requests merged in 2019-06, with the labels that each got.

#250 refactor: Set default template to the generic packer
  packages/teleport-project-generator-react-basic/src/index.ts
  packages/teleport-project-generator-react-next/src/index.ts
  packages/teleport-project-generator-vue-basic/src/index.ts
  packages/teleport-project-generator-vue-nuxt/src/index.ts
  packages/teleport-project-packer-test/src/index.ts
  packages/teleport-project-packer/__tests__/index.ts
  packages/teleport-project-packer/src/constants.ts
  packages/teleport-project-packer/src/errors.ts
  packages/teleport-project-packer/src/index.ts
  packages/teleport-shared/src/utils/project-utils.ts
  packages/teleport-types/src/generators.ts
Labels: refactoring

#252 fix(github-packer): Added master branch and check for commit branch
  packages/teleport-publisher-github/src/index.ts
Labels: bug, packer

#257 refactor(now/src): Changes the name to accessToken from deployToken
  packages/teleport-publisher-now/__tests__/index.ts
  packages/teleport-publisher-now/src/errors.ts
  packages/teleport-publisher-now/src/index.ts
Labels: packer

#260 chore(packer-test): Used a config file to display the github token
  .gitignore
  README.md
  packages/teleport-project-packer-test/src/config.example.json
  packages/teleport-project-packer-test/src/index.ts
Labels: dev experience

#266 fix(styled-jsx/index): Injecting style in first child if root is non element
  packages/teleport-plugin-react-styled-jsx/__tests__/index.ts
  packages/teleport-plugin-react-styled-jsx/src/index.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
Labels: bug

#261 fix(uidl/comp): Validating content if the parent type is static
  packages/teleport-uidl-validator/src/uidl-schemas/component.json
Labels: bug

#279 Fix/vue default values
  packages/teleport-component-generator/__tests__/resolver/utils.ts
  packages/teleport-component-generator/src/resolver/index.ts
  packages/teleport-component-generator/src/resolver/utils.ts
  packages/teleport-plugin-vue-base-component/__tests__/index.ts
  packages/teleport-plugin-vue-base-component/__tests__/mocks.ts
  packages/teleport-plugin-vue-base-component/src/constants.ts
  packages/teleport-plugin-vue-base-component/src/index.ts
  packages/teleport-plugin-vue-base-component/src/utils.ts
  packages/teleport-shared/src/utils/ast-js-utils.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
Labels: vue generators

#282 feat: Decode github files using a whitelist
  packages/teleport-github-gateway/src/constants.ts
  packages/teleport-github-gateway/src/utils.ts
Labels: packer

#278 feat(Attribute-mapping): Adding mapping for attributes
  packages/teleport-component-generator-react/__tests__/integration/component-attrs.ts
  packages/teleport-component-generator-react/src/react-mapping.json
  packages/teleport-component-generator-vue/__tests__/integration/component-attrs.ts
  packages/teleport-component-generator-vue/src/vue-mapping.json
  packages/teleport-component-generator/__tests__/resolver/index.ts
  packages/teleport-component-generator/src/html-mapping.json
  packages/teleport-component-generator/src/resolver/index.ts
  packages/teleport-component-generator/src/resolver/utils.ts
  packages/teleport-types/src/uidl.ts
Labels: enhancement

#281 feat(proj-gen): implement local dependency resolver for components an…
  .prettierignore
  examples/uidl-samples/project.json
  packages/teleport-component-generator-react/__tests__/performance/index.ts
  packages/teleport-component-generator-vue/__tests__/performance/index.ts
  packages/teleport-component-generator/src/index.ts
  packages/teleport-project-generator/__tests__/index.ts
  packages/teleport-project-generator/src/index.ts
  packages/teleport-project-generator/src/types.ts
  packages/teleport-project-generator/src/utils.ts
  packages/teleport-shared/__tests__/utils/uidl-utils.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
  packages/teleport-types/src/uidl.ts
Labels: enhancement

#290 fix(uidl): filename derived from sanitized component name
  packages/teleport-component-generator/src/index.ts
  packages/teleport-uidl-validator/src/uidl-schemas/component.json
Labels: bug

#291 fix(proj-gen): check for file override instead of duplication
  packages/teleport-project-generator/__tests__/mocks.ts
  packages/teleport-project-generator/__tests__/utils.ts
  packages/teleport-project-generator/src/utils.ts
Labels: bug

#289 Fix/small updates in plugins
  examples/uidl-samples/project.json
  packages/teleport-component-generator/src/builder/index.ts
  packages/teleport-component-generator/src/html-mapping.json
  packages/teleport-component-generator/src/resolver/utils.ts
  packages/teleport-plugin-react-base-component/src/utils.ts
  packages/teleport-plugin-react-proptypes/src/utils.ts
  packages/teleport-plugin-vue-base-component/src/utils.ts
  packages/teleport-postprocessor-vue-file/__tests__/index.ts
  packages/teleport-postprocessor-vue-file/src/index.ts
  packages/teleport-shared/__tests__/utils/uidl-utils.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-uidl-validator/__tests__/validator/component-invalid-sample.json
  packages/teleport-uidl-validator/src/validator/utils.ts
Labels: bug
