Repository teleporthq/teleport-code-generators, pull requests merged in 2020-10, with the labels that each got.

#486 Fix broken link in readme
  README.md
Labels: documentation

#490 refactor(publisher-vercel): rename from now to vercel
  README.md
  packages/teleport-code-generator/package.json
  packages/teleport-code-generator/src/index.ts
  packages/teleport-publisher-vercel/README.md
  packages/teleport-publisher-vercel/__tests__/index.ts
  packages/teleport-publisher-vercel/__tests__/project-files.json
  packages/teleport-publisher-vercel/package.json
  packages/teleport-publisher-vercel/src/index.ts
  packages/teleport-publisher-vercel/src/types.ts
  packages/teleport-publisher-vercel/src/utils.ts
  packages/teleport-publisher-vercel/tsconfig-cjs.json
  packages/teleport-publisher-vercel/tsconfig-esm.json
  packages/teleport-types/src/errors.ts
  packages/teleport-types/src/generators.ts
Labels: refactoring

#491 refactor(html-mappings): add linebreak to html mappings
  packages/teleport-uidl-resolver/src/html-mapping.json
Labels: bug

#496 fix(angular-base): ignore imports for frameworks like angular which are imported directly in modules
  examples/test-samples/project-sample-with-dependency.json
  examples/test-samples/project-with-import-global-styles.json
  packages/teleport-plugin-common/src/node-handlers/node-to-html/index.ts
  packages/teleport-project-generator-angular/__tests__/end2end/index.ts
  packages/teleport-project-generator-gatsby/__tests__/end2end/index.ts
  packages/teleport-project-generator-gridsome/__tests__/end2end/index.ts
  packages/teleport-project-generator-next/__tests__/end2end/index.ts
  packages/teleport-project-generator-nuxt/__tests__/end2end/index.ts
  packages/teleport-project-generator-preact/__tests__/end2end/index.ts
  packages/teleport-project-generator-react/__tests__/end2end/index.ts
  packages/teleport-project-generator-stencil/__tests__/end2end/index.ts
  packages/teleport-project-generator-vue/__tests__/end2end/index.ts
Labels: angular generators, bug

#493 fix: addAttributeToJSXTag when attr's value is boolean
  packages/teleport-plugin-common/__tests__/node-handlers/node-to-html/utils.ts
  packages/teleport-plugin-common/__tests__/utils/ast-utils.ts
  packages/teleport-plugin-common/src/node-handlers/node-to-html/utils.ts
  packages/teleport-plugin-common/src/utils/ast-utils.ts
  packages/teleport-plugin-common/src/utils/hast-utils.ts
Labels: bug
