Repository teleporthq/teleport-code-generators, pull requests merged in 2021-04, with the labels that each got.

#555 fix(github-publisher): changing default branch to main instead of master
  packages/teleport-publisher-github/__tests__/index.ts
  packages/teleport-publisher-github/src/index.ts
  packages/teleport-publisher-github/src/types.ts
  packages/teleport-publisher-github/src/utils.ts
Labels: bug, packer

#558 fix(plugin-css): add contents by default for shadow DOM and custom elments based frameworks
  packages/teleport-plugin-css/src/index.ts
Labels: bug

#560 (refactor): Extending validations for events in UIDL
  packages/teleport-component-generator-angular/__tests__/end2end/index.ts
  packages/teleport-component-generator-vue/__tests__/end2end/index.ts
  packages/teleport-plugin-angular-base-component/src/utils.ts
  packages/teleport-plugin-common/src/builders/ast-builders.ts
  packages/teleport-plugin-common/src/node-handlers/node-to-html/utils.ts
  packages/teleport-plugin-common/src/node-handlers/node-to-jsx/utils.ts
  packages/teleport-plugin-vue-base-component/src/utils.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-uidl-validator/__tests__/validator/component-uidl-with-event-modifier-undefined.json
  packages/teleport-uidl-validator/__tests__/validator/index.ts
  packages/teleport-uidl-validator/src/decoders/utils.ts
  packages/teleport-uidl-validator/src/validator/utils.ts
Labels: uidl

#563 fix(generator): enable jsec encoding to support special characters in AST to code transformation
  packages/teleport-component-generator/src/builder/generators/js-ast-to-code.ts
Labels: core, refactoring
