Repository teleporthq/teleport-code-generators, pull requests merged in 2022-02, with the labels that each got.

#645 Small fix for Vercel deploy
  packages/teleport-publisher-vercel/src/utils.ts
Labels: bug

#644 fix(plugin-css): force scope comp-style references on component instances for vanilla css flavour
  examples/test-samples/comp-style-overrides.json
  packages/teleport-plugin-common/src/builders/style-builders.ts
  packages/teleport-plugin-common/src/node-handlers/node-to-html/utils.ts
  packages/teleport-plugin-common/src/node-handlers/node-to-jsx/index.ts
  packages/teleport-plugin-css-modules/src/index.ts
  packages/teleport-plugin-css-modules/src/style-sheet.ts
  packages/teleport-plugin-css/src/index.ts
  packages/teleport-plugin-css/src/style-sheet.ts
  packages/teleport-plugin-react-styled-jsx/src/index.ts
  packages/teleport-project-generator-html/__tests__/index.ts
  packages/teleport-project-generator-react/__tests__/end2end/index.ts
  packages/teleport-shared/src/utils/uidl-utils.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-uidl-resolver/src/utils.ts
  packages/teleport-uidl-validator/src/decoders/utils.ts
  packages/teleport-uidl-validator/src/validator/utils.ts
Labels: style flavours

#650 chore(proj-next): upgrading to latest version of nextjs for deployments
  packages/teleport-project-generator-next/src/next-project-mapping.ts
  packages/teleport-project-generator-next/src/project-template.ts
  packages/teleport-test/src/component.ts
  packages/teleport-uidl-builders/src/component-builders.ts
Labels: enhancement
