Repository teleporthq/teleport-code-generators, pull requests merged in 2022-03, with the labels that each got.

#657 feat(uidl): add ability to pass additional attrs to html tags
  examples/test-samples/project-sample.json
  examples/uidl-samples/project.json
  examples/uidl-samples/react-project.json
  examples/uidl-samples/simple-html.json
  packages/teleport-plugin-common/src/builders/ast-builders.ts
  packages/teleport-project-generator-react/__tests__/end2end/index.ts
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-types/src/uidl.ts
  packages/teleport-types/src/vuidl.ts
  packages/teleport-uidl-validator/__tests__/validator/index.ts
  packages/teleport-uidl-validator/__tests__/validator/project-sample.json
  packages/teleport-uidl-validator/src/decoders/project-decoder.ts
  packages/teleport-uidl-validator/src/decoders/utils.ts
  packages/teleport-uidl-validator/src/parser/index.ts
  packages/teleport-uidl-validator/src/validator/index.ts
Labels: core

#660 refactor(github-gateway): use octokit to create file blobs before committing the files
  packages/teleport-github-gateway/src/constants.ts
  packages/teleport-github-gateway/src/github-instance.ts
  packages/teleport-github-gateway/src/utils.ts
Labels: refactoring

#662 fix(core): fixing memory leaks and missing Output imports for angular generators
  examples/uidl-samples/react-project.json
  packages/teleport-code-generator/__tests__/index.ts
  packages/teleport-code-generator/src/index.ts
  packages/teleport-plugin-angular-base-component/src/index.ts
  packages/teleport-project-generator-gatsby/src/utils.ts
  packages/teleport-project-generator/src/file-handlers.ts
  packages/teleport-project-generator/src/index.ts
  packages/teleport-test/src/standalone.ts
  packages/teleport-uidl-resolver/src/resolvers/abilities/utils.ts
Labels: bug

#663 (fix): Trailing space for teleport-project-plugin-styled-components folder
  packages/teleport-plugin-css-modules/__tests__/component-scoped.ts
  packages/teleport-project-plugin-react-styled-components/package.json
  packages/teleport-project-plugin-react-styled-components/src/index.ts
  packages/teleport-project-plugin-react-styled-components/tsconfig.json
Labels: bug

#664 fix(proj-html): fixes html generator and route mapping for html routes
  examples/uidl-samples/simple-html.json
  packages/teleport-code-generator/__tests__/index.ts
  packages/teleport-code-generator/src/index.ts
  packages/teleport-plugin-html-base-component/__tests__/index.ts
  packages/teleport-plugin-html-base-component/src/node-handlers.ts
  packages/teleport-project-generator-html/src/index.ts
  packages/teleport-project-generator-html/src/plugin-clone-globals.ts
  packages/teleport-project-generator-html/src/plugin-image-resolution.ts
  packages/teleport-test/src/standalone.ts
Labels: bug

#669 (fix): Enable scoping for styled-jsx for components and disable scoping for global styles in next
  packages/teleport-code-generator/__tests__/end2end/index.ts
  packages/teleport-component-generator-angular/__tests__/end2end/component-referenced-styles.ts
  packages/teleport-component-generator-react/__tests__/integration/component-referenced-styles.ts
  packages/teleport-component-generator-react/src/index.ts
  packages/teleport-component-generator-vue/__tests__/integration/component-referenced-styles.ts
  packages/teleport-plugin-common/src/builders/style-builders.ts
  packages/teleport-plugin-css-modules/__tests__/component-scoped.ts
  packages/teleport-plugin-css-modules/__tests__/style-sheet.ts
  packages/teleport-plugin-css-modules/src/index.ts
  packages/teleport-plugin-css/__tests__/component-scoped.ts
  packages/teleport-plugin-css/__tests__/referenced-styles.ts
  packages/teleport-plugin-css/__tests__/style-sheet.ts
  packages/teleport-plugin-css/src/index.ts
  packages/teleport-plugin-css/src/style-sheet.ts
  packages/teleport-plugin-react-jss/__tests__/component-referenced.ts
  packages/teleport-plugin-react-jss/src/index.ts
  packages/teleport-plugin-react-jss/src/utils.ts
  packages/teleport-plugin-react-styled-components/src/index.ts
  packages/teleport-plugin-react-styled-components/src/utils.ts
  packages/teleport-plugin-react-styled-jsx/__tests__/component-scoped.ts
  packages/teleport-plugin-react-styled-jsx/src/index.ts
  packages/teleport-project-generator-gridsome/__tests__/end2end/index.ts
  packages/teleport-project-generator-next/src/index.ts
  packages/teleport-project-packer/src/index.ts
  packages/teleport-project-plugin-next-css-modules/src/index.ts
Labels: bug
